services:
  - type: web
    name: harvestify-backend
    runtime: image
    rootDir: backend
    image:
      dockerfilePath: Dockerfile
    envVars:
      - key: FLASK_ENV
        value: production
      - key: MONGODB_URI
        sync: false
      - key: JWT_SECRET_KEY
        generateValue: true
      - key: SECRET_KEY
        generateValue: true
      - key: WEATHER_API_KEY
        sync: false
      - key: GEMINI_API_KEY
        sync: false
      - key: CLOUDINARY_CLOUD_NAME
        sync: false
      - key: CLOUDINARY_API_KEY
        sync: false
      - key: CLOUDINARY_API_SECRET
        sync: false
      - key: EMAIL_USER
        sync: false
      - key: EMAIL_PASS
        sync: false
      - key: BASE_URL
        sync: false
