from app.routes import auth
from app.routes import crops
from app.routes import fertilizer
from app.routes import products
from app.routes import orders
from app.routes import profile
from app.routes import admin
from app.routes import weather
from app.routes import doctor
from app.routes import user